repos:
#  - repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: v4.4.0
#    hooks:
#    -   id: trailing-whitespace
#    -   id: end-of-file-fixer
#    -   id: check-yaml
#    -   id: check-added-large-files
#    -   id: check-ast
#    -   id: check-merge-conflict
#  - repo: https://github.com/pre-commit/mirrors-isort
#    rev: v5.10.1
#    hooks:
#      - id: isort
#        args: ["--profile", "black"]
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.4.1
#    hooks:
#      - id: mypy
#        exclude: mantis/tests/
#        args:
#          - --follow-imports=skip
#          - --ignore-missing-imports
#          - --show-error-codes
#        additional_dependencies:
#          - types-requests
#          - types-chardet
#          - types-python-dateutil
#          - types-redis
#          - types-six
#          - types-boto
#          - types-retry
#          - types-backports
#          - types-pytz
#          - types-paramiko
#          - types-attrs
#          - types-frozendict
#          - types-simplejson
#          - types-mock
#  - repo: https://github.com/pycqa/flake8.git
#    rev: 6.0.0
#    hooks:
#      - id: flake8
#        additional_dependencies:
#          - flake8-bugbear
#        # Only pyflakes (bugs and no style checks)
#        # Ignore -
#        #   Module imported but unused (F401)
#        #   Name may be undefined, or defined from star imports: module (F405)
#        #   Local variable name is assigned to but never used (F841)
#        #   'from module import *' used; unable to detect undefined names (F403)
#        #   Redefinition of unused name from line n (F811)
#        #   raise NotImplemented should be raise NotImplementedError (F901)
#        args: [ --max-line-length, "120", --select, F, --ignore, "F401,F405,F841,F403,F811,F901" ]
#        language_version: python3
#  - repo: https://github.com/PyCQA/autoflake.git
#    rev: v1.4
#    hooks:
#      - id: autoflake
#        args:
#          - --in-place
#          - --remove-unused-variables
#          - --remove-all-unused-imports
#          - --ignore-init-module-imports
#          - --remove-duplicate-keys
#        language_version: python3
#        additional_dependencies:
#          - pyflakes>=1.1.0,<3
#  - repo: https://github.com/asottile/pyupgrade
#    rev: v3.7.0
#    hooks:
#      - id: pyupgrade
#  - repo: https://github.com/python/black.git
#    rev: 23.3.0
#    hooks:
#      - id: black
#        language_version: python3
#        args: [--skip-string-normalization, --line-length, "120"]
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.14.1
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.2"]
